### PR TITLE
added client.set case using force option in order to clarify how to u…

### PR DESCRIPTION
**Pull request by joecabezas**
…se this option since they are 2 positional hash arguments

### CODE REVIEW

**Comment by joecabezas** [comment]
related issue:
https://github.com/checkr/stasche/issues/24

**Comment by jperichon** [comment]
did you not check in the code fix?

**Comment by rstratton** [comment]
@jperichon I believe the intent is to just add an example of how to use the `force` option in tests.  Actually @joecabezas would you mind adding an example to the README as well?

**Comment by joecabezas** [comment]
Added example to the `README.md` too

**Pull request merged**
